version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: stock_db
    ports:
      - "5432:5432"
    restart: always
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: 2.0.0
      labels:
        - "version=2.0.0"
    image: abraxel/stock-automation:2.0.0
    container_name: spring-app-container
    ports:
      - "8080:8080"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/stock_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - postgres-db
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_data:
